### PR TITLE
#19 add support from `a` and `p` keys to change day period

### PR DESCRIPTION
**Pull request by LiniovasDovydas**
Closes https://github.com/dan-lee/timescape/issues/19

Could not check if it works in storybook due to errors, maybe because I am on windows, but tests seem to run fine, if you could check I'd be grateful 🙂.

```
PS C:\other\timescape> pnpm demo

> @timescape/root@0.0.0 demo C:\other\timescape
> pnpm --filter demo run dev


> demo@1.2.3 dev C:\other\timescape\packages\demo
> concurrently -n 'integration,storybook' 'pnpm vite --port 4949' 'pnpm storybook:dev --no-open'

['integration] ''pnpm' is not recognized as an internal or external command,
['integration] operable program or batch file.
[2] ''pnpm' is not recognized as an internal or external command,
[2] operable program or batch file.
[2] 'pnpm exited with code 1
['integration] 'pnpm exited with code 1
[3] The filename, directory name, or volume label syntax is incorrect.
[3] storybook:dev exited with code 1
```

### CODE REVIEW

**Comment by dan-lee** [comment]
Hey @LiniovasDovydas,
thank you so much for reporting this issue and also sending a PR :)
That's definitely an oversight, I'll take a look asap!

Also sidenote:

Interesting that `pnpm` works when you call it yourself, but not when called from `concurrently`. Perhaps you could try running both commands in separate terminals:

```
pnpm vite --port 4949
pnpm storybook:dev --no-open
```

**Review by dan-lee — APPROVED** [review]
This is a good fix, thanks for contributing! 🚀 
I [also snuck in a fix](https://github.com/dan-lee/timescape/pull/20/commits/e484247b299ffd2c552fc88713f396d890621ba6) that prevents any other characters from being typed into this field

In the longer term, I wonder if there's a way where we could provide a similar experience to what a `<select>` field gives on a mobile browser, like so:

image

**Comment by dan-lee** [comment]
Released in https://github.com/dan-lee/timescape/releases/tag/timescape%400.4.4 🚀

**Comment by LiniovasDovydas** [comment]
Nice! After creating the PR I thought about the preventing characters case, but you beat me to it 😄.

Regarding the `<select />` the only issue I see is that the web options are not stylable yet. The package could export utility to switch to `AM/PM` and the package handles the switch, so the UI is left for the user to create what ever experience he wants.

```tsx
const { setDayPeriod } = useTimescape({ ... })

setDayPeriod('AM');
setDayPeriod('PM');
```

**Pull request merged**
